channels:
  - name: "AI時代の羅針盤"
    id: "UCe5LyrwsMmTU1OebzUv69vQ"
    handle: "@compassinai"
  - name: "AWS資格 対策講座"
    id: "UCV3Y915Y_108vQ25qC_sC3w"
    handle: "@AWS_course"
  - name: "にゃんたのAIチャンネル"
    id: "UCj_OQk8d4qG_4gZp1G8yS6g"
    handle: "@aivtuber2866"
